### PR TITLE
Milestone: Friendships v1 

### PR DESCRIPTION
**Pull request by verissimohenry**
Create a model with associations and all requested features for friendships.

### CODE REVIEW

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
Hi @verissimohenry, :hand: :hand: :hand:  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [x] User can invite friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/send_invitation.png) from Pathwright) => I did not see where to send friendship requests

- [x] User can see friendships requests ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/pending_request.png) from Pathwright)

- [x] User has to accept friendship request to start friendship ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from Pathwright)

- [x] User can reject a friendship request ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from Pathwright)

- [x] There is a button to invite user to friendship on users list page and on single user page ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png) from Pathwright) => this button is missing on neither users list page nor a given user profile page, 

- [x] Posts timeline includes posts written by logged-in user and their friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from Pathwright) => currently all posts are being shown by default on all pages

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [x] It would be very nice if you add the currently logged in username in the navbar
- [x] It would be very great if you install tests to run on the github actions of your repository

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_Any thing unclear to you, please write a comment right in this PR thread, and mention me as [@descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond!_

**Review by george-shammar — CHANGES_REQUESTED** [review]
### **STATUS:CHANGES REQUIRED** :recycle: :recycle: :construction: :construction_worker_man: 

You're making effort. Please keep it up. :+1: 

All the requested changes from the previous review has not been implemented. For emphasis, I'll repeat the requested changes here:

- [ ] Users should be able to invite friends. There is no where on project where I can do that.
- [ ] A user should be able to see friendship requests.
- [ ] A user should be able to accept friendship request to start friendship.
- [ ] A user should be able to reject friendship request to end a friendship.
- [ ] There is a button to invite user to friendship on users list page and on single user page.
- [ ] Posts timeline should only include posts written by logged-in user and their friends.

Please make the required changes and submit another CRR when you're ready.

If you need help or require clarification, please drop your message here or hit me up on slack.

Cheers and happy coding :smile:

**Review by ElijahTobs — CHANGES_REQUESTED** [review]
# Status: Changes Required ⚠️ 🚦
## Hi @verissimohenry  👋

**Just as pointed out by the 2 previous code reviewers, kindly make the following changes in order to get this milestone approved.**

## Required Changes ♻️

- [x] Users should be able to invite friends. There is no where on project where I can do that.
- [x] A user should be able to see friendship requests.
- [x] A user should be able to accept friendship request to start friendship.
- [x] A user should be able to reject friendship request to end a friendship.
- [x] There is a button to invite user to friendship on users list page and on single user page.
- [x] Posts timeline should only include posts written by logged-in user and their friends.

#### If anything doesn't seem clear to you, feel free to leave your question or comment in the PR thread below

#### "Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise."

## Happy Coding :computer: 

_Reviewed by_  **Elijah O. Ayandokun**

**Review by elisha2kyakpo1 — CHANGES_REQUESTED** [review]
# Required Changes ♻️

Just as pointed out by the previous code reviewers, kindly make the following changes before we move.

- [x]  Users should be able to invite friends. There is no where on project where I can do that.
- [x] A user should be able to see friendship requests.
- [x] A user should be able to accept friendship request to start friendship.
- [x]  A user should be able to reject friendship request to end a friendship.
- [x]  There is a button to invite user to friendship on users list page and on single user page.
- [x] Posts timeline should only include posts written by logged-in user and their friends.
- [x] Users should be able to invite friends. There is nowhere on the project where I can do that.
- [x] A user should be able to see friendship requests.
- [x] A user should be able to accept a friendship request to start a friendship.
- [x] A user should be able to reject a friendship request to end a friendship.
- [x] There is a button to invite user to friendship on users list page and on the single-user page.
- [x] Posts timeline should only include posts written by logged-in user and their friends.

**Please make all the changes before submitting another PR for review**

<hr>
**In case you need any help, I'm always available to assist**

Cheers✔🎉💪

Elisha kyakopo

**Review by george-shammar — APPROVED** [review]
### **STATUS:APPROVED** :heavy_check_mark: :heavy_check_mark: 

Congratulations and good job. Thank you for implementing the requested changes. :+1: :clap: 

All the functionalities are working as expected.

You may go ahead and merge this branch and proceed to the next milestone.

Cheers and happy coding. :smile:

**Pull request merged**
