### PR TITLE
Milestone friendships v2

### PR DESCRIPTION
**Pull request by verissimohenry**
Implement friendships with 2 rows for mutual friendship.
Add unit and integrations tests!

### CODE REVIEW

**Review by elisha2kyakpo1 — CHANGES_REQUESTED** [review]
# Status: Changes required👈👈

Hey @verissimohenry, you have done a good job, let's just fix one issue so that we can move.

## To Highlight:

- A user can send/receive friend requests.
- A user can accept/reject friend requests.
- A user can unfriend an existing friend.
- I can only see my posts and that of my friends.

## Changes to make.

- [x] When I click add friend button, I get a routing error.

**[OPTIONAL]**

- [x] Try to give the friendship model a meaningful name, it can even help when debugging. Friendss is not a good name.

<hr>
Please make the changes and submit another review request

I'm always available on slack, in case you have a question, just search for Elisha kyakopo

Cheers🎉💪

**Review by SajjadAhmad14 — CHANGES_REQUESTED** [review]
# Changes Required :recycle:
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hello, you have been doing a tremendous job so far :ok_hand:
## To Highlight 🎉
- [x] You have mastered Git flow.
- [x] README includes all the steps to run the project locally.
## To Improve 🙏
- [x] I send a friendship request from user A to user B, but User B has no functionality to accept or reject it. Moreover, I get this error when user B is logged in and I click on B's show page I get this error:
show-page-error
- [x] User can unfriend his friends.
- [x] User can only see his own posts and that of his friends.
- [x] Please add unit tests for User and integration tests for friendship functionality.
- [x] NOTE: "You have not started implementing friendships v2 milestone'. Please read [this](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/
) and work on all the requirements of the current milestone and ask for another code review when you are done"
### Happy Coding ☺️

## If you have any questions you can comment here in this PR or can always connect with me on slack ( @Sajjad Ahmad ).

**Review by carlos-ssh — CHANGES_REQUESTED** [review]
Hello @verissimohenry 👋🏽✌🏽 I like your project is very impressive.
Keep working hard! 🧠🥷🏽👨🏽‍💻

Please help me with a few changes:
- Into application_helper line 66:
```
  user.id]).where(friend_id: [current_user.id,
```
this is affecting your Users#show in the line 40:
```
<li><%= friend.name%><%= unfriend_btn(@friend)%></li>
```
<hr>
<strong>Once that you finish this. Remember to run your tests with RSpec before to create a new pull request.</strong>
<hr>
Happy Coding! 👾
<br>
@Carlos-SSH

**Comment by verissimohenry** [comment]
ok, thank you.

**Review by carlos-ssh — CHANGES_REQUESTED** [review]
Hello @verissimohenry it's me again! 😄✌🏽
Your changes are making that your project looks great!.👏🏽👏🏽👏🏽

When I ran locally your project the friend request is working now.
But when I try to go to my friends profile I receive this error: 
Screen Shot 2021-06-02 at 07 15 25

Please help me to fix this.
Once that finished the requested changes in your project please request a CR again.

_Happy Coding!_ 👾👨🏽‍💻
@carlos-ssh

**Comment by verissimohenry** [comment]
I'm kinda stuck. don't know why it's still showing that error.

**Comment by carlos-ssh** [comment]
Hello @verissimohenry  Please write me on Slack: Carlos Robles.

**Review by BrianSammit — APPROVED** [review]
STATUS APPROVED :green_circle: :clap: 
-------------
Hello @verissimohenry Great job working on the required changes :+1: :100: 
Your project is really nice :muscle: 
----------
Now you can merge this branch :+1: 
HAPPY CODING!!! AND GOOD LUCK WITH THE COMMING ONES :+1: :100:

**Pull request merged**
